### ISSUE TITLE
cmake errors with cygwin on Win 7

### ISSUE THREAD

**Issue by dansbecker** [piratical/Madeline_2.0_PDE#37]
I'm trying to help my wife (who works with Tasha Fingerlin) install Madeline 2 on a Windows 7 machine.  We are following the instructions at http://madeline.med.umich.edu/madeline/install.php

We've hit a roadblock in the installation, and neither of us has much experience debugging this type of install. So any guidance would be appreciated (and we recognize that development has primarily happened on osx and linux).

For the cygwin installation, we downloaded the 64-bit cygwin. I think we've been able to follow the instructions quite literally.  In many cases, their were multiple versions of the required packages available during cygwin installation.  When that happened, we download the version with lib in the name (the other versions of those packages were under the debug, perl or python directories).

At the configure stage, when we run `cmake .` we get the following error:

```
CMake Warning at /usr/share/cmake-3.6.2/Modules/Platform/CYGWIN.cmake:15 (message):
  CMake no longer defines WIN32 on Cygwin!

  (1) If you are just trying to build this project, ignore this warning or
  quiet it by setting CMAKE_LEGACY_CYGWIN_WIN32=0 in your environment or in
  the CMake cache.  If later configuration or build errors occur then this
  project may have been written under the assumption that Cygwin is WIN32.
  In that case, set CMAKE_LEGACY_CYGWIN_WIN32=1 instead.

  (2) If you are developing this project, add the line

    set(CMAKE_LEGACY_CYGWIN_WIN32 0) # Remove when CMake >= 2.8.4 is required

  at the top of your top-level CMakeLists.txt file or set the minimum
  required version of CMake to 2.8.4 or higher.  Then teach your project to
  build on Cygwin without WIN32.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:8 (PROJECT)


-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
-- === NOTA BENE: === Madeline will use included bzip2
CMake Error at /usr/share/cmake-3.6.2/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.6.2/Modules/FindZLIB.cmake:124 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:259 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/powersju/Madeline_2.0_PDE/CMakeFiles/CMakeOutput.log".
See also "/home/powersju/Madeline_2.0_PDE/CMakeFiles/CMakeError.log".
```

CMakeOutput.log is quite a long file, so I've put it in [this gist](https://gist.github.com/dansbecker/28e104baa8d6b31f58dc83ff084cf606)
[Here](https://gist.github.com/dansbecker/280f18e1efcaee1d281dce2fa8e9bf2f) is the content of CMakeError.log 

Again, thank you so much for any suggestions or help.

**Comment by piratical** [comment]
This may be fixed by the latest patch from ito-k which has now been merged into the master branch.

**Comment by dansbecker** [comment]
Thanks.  

She set up a VM with Ubuntu. I'll suggest she retest the windows installation so we can post back here with a confirmation that this fix works, and then I'll close the issue. In her case specifically, she's happy with the VM solution, and likely will continue using that even if this works in Windows.

Thanks again.
