### ISSUE TITLE
Madeline 2.0 PDE : information retrieval from Mysql Database

### ISSUE THREAD

**Issue by meetannada** [piratical/Madeline_2.0_PDE#47]
This is Annapoorna, from The University of Transdisciplinary Health Sciences and Technology (TDU), Bangalore, India ; wishing you a Very Happy and Healthy 2021. I write to you today asking for assistance with regard to your pedigree drawing engine Madeline 2.0

I am presently working on a project that requires using pedigrees for studying inheritance patterns of genetic traits. Madeline 2.0 seems to be an excellent choice to do this, however, I am unable to find information regarding how  Madeline 2.0 is able to read data  from a Mysql data table. The information brochure found online, i.e Madeline 2.0 PDE Docs, states it can do so but does not elaborate.

I request you to please guide me in this regard. Looking forward to hearing from you.

**Comment by piratical** [comment]
Hi, Annapoorna,

The best approach would be for you to export the data out of MySQL and format it in one of the file formats that Madeline2 is able to read. Although some initial work was done to support pulling data from MySQL many years ago, this feature was never fully tested or maintained. I'm not sure if it still works with more recent versions of MySQL or not. In any case, there is no real documentation on this feature and no plans to support it going forward.
