### ISSUE TITLE
Mother-son matings

### ISSUE THREAD

**Issue by andersonwinkler** [piratical/Madeline_2.0_PDE#48]
Thank you for this wonderful program. Mother-son and father-daughter relationships are rare among humans but not so among animals and plants. Mythology is full of these cases too (I know, it'd be an unintended use of the program). Still, any chance such cases of inbreeding could become available? Consider this famous and relatively simple pedigree:

FamilyId | IndividualId | Gender | Father | Mother
-- | -- | -- | -- | --
1 | Oedipus | M | Laius | Jocasta
1 | Polyneices | M | Oedipus | Jocasta
1 | Eteocles | M | Oedipus | Jocasta
1 | Ismene | F | Oedipus | Jocasta
1 | Antigone | F | Oedipus | Jocasta

If we try to run, we receive:

```
Unrecoverable Error: Individual::addSpouse(): Oedipus's spouse Jocasta is also his mother: Program currently cannot handle mother-son matings.
terminate called after throwing an instance of 'Exception'
Aborted (core dumped)
```

Thanks!

**Comment by piratical** [comment]
Unfortunately I am busy on other projects at the moment. I had considered
these issues sufficiently to produce the coherent error messages which you
saw, but it seems like actually solving the issues will require a lot of
work, which at the moment I don't have time to do.

You are of course welcome to dig into the code and propose solutions if you
want to.

Best Wishes -- Ed Trager

**Comment by andersonwinkler** [comment]
Dear Ed,
Thank you for the feedback. It doesn't seem straightforward -- needs familiarity with the code. I appreciate nonetheless.
All the best,
Anderson
